### ISSUE TITLE
Warning show only "link quality" message

### ISSUE THREAD

**Issue by Quickred** [mbilozub/fpv_custom_mods#1]
Thanks for the mod, my friend and I have installed the custom firmware on 2 different fc's (MatekF722se and HGLRCF722). 

We get both the warning message "LINK QUALITY" and not "BATT<FULL". The Error was, that we have both activated "Link quality" in the OSD warnings. After removing the button, the message "BATT<FULL" appers. So everything works!

Thank you very much for your support

![2021-03-20 13 44 54-1_small](https://user-images.githubusercontent.com/10882205/111870837-33f1b180-8987-11eb-9572-104c5cb429f6.jpg)

![image](https://user-images.githubusercontent.com/10882205/111870616-09ebbf80-8986-11eb-96c5-a0ad94366982.png)

![2021-03-20 13 59 47-small](https://user-images.githubusercontent.com/10882205/111870841-394efc00-8987-11eb-9586-dc7673c6341e.jpg)

**Comment by C3TAX** [comment]
Hi, first of all thank you very much. The OSD works great.
Thanks :-)

Quickred and I very Happy..

**Comment by mbilozub** [comment]
Hmmm. I also saw this error but only when I did not set up the LQ correctly. But there is another problem - DJI OSD does not show LQ. Quick fix - display the value of LQ in the RSSI field (https://youtu.be/sYafWt-c7dQ). Maybe later I'll make the values ​​automatically appear in RSSI when the show_lq_instead_rssi parameter or something similar is set.

**Comment by C3TAX** [comment]
Hi, I just saw you built the 4.3. :-)
I flash them and and will test. I'll report tomorrow.
Thank you, great job.
That’s really great.
